name: Generate Table of Contents

on:
  workflow_dispatch:
    branches:
      - master

permissions:
  contents: write

jobs:
  generate-toc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install doctoc
        run: npm install -g doctoc

      - name: Generate TOC for README.md
        run: |
          if [ -f ./README.md ]; then
            doctoc ./README.md --title '**Table of Contents**' || echo "Failed to generate TOC for README.md"
          else
            echo "README.md not found, skipping"
          fi

      - name: Generate TOC for Project_summary.md
        run: |
          if [ -f ./docs/Project_summary.md ]; then
            doctoc ./docs/Project_summary.md --title '**Table of Contents**' || echo "Failed to generate TOC for Project_summary.md"
          else
            echo "docs/Project_summary.md not found, skipping"
          fi

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md docs/Project_summary.md || true
          if git status --porcelain | grep .; then
            git commit -m 'Update Table of Contents for Markdown files'
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
